openapi: 3.0.3
info:
  title: Swagger Candle - OpenAPI 3.0
  description: |-
    HackU KOSEN 2023:
    Candle Backend
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
#TODO: change url to our server
  - url: https://petstore3.swagger.io/api/v3
security:
  - OAuth2:
    - read
    - write
tags:
  - name: user
  - name: candle
  - name: photo
  - name: mosaic_art

paths:
    /user/{user_id}:
      get:
        tags:
          - user
        summary: "Get user information"
        description: "Retrieve user information by user ID"
        parameters:
          - in: path
            name: user_id
            required: true
            schema:
              type: string

        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
          '500':
            description: "Internal Server Error"
      put:
        tags:
          - user
        summary: "Update user information"
        description: "Update user information by user ID"
        parameters:
          - in: path
            name: user_id
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
          '500':
            description: "Internal Server Error"
    /candle/{user_id}:
      get:
        tags:
          - candle
        summary: "Get candle information"
        description: "Retrieve candle information by user ID"
        parameters:
          - in: path
            name: user_id
            required: true
            schema:
              type: string
        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/candle'
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
          '500':
            description: "Internal Server Error"
      put:
        tags:
          - candle
        summary: "Update candle information"
        description: "Update candle information by user ID"
        parameters:
          - in: path
            name: user_id
            required: true
            schema:
              type: string
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/candle'
        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/candle'
          '401':
            description: "Unauthorized"
          '500':
            description: "Internal Server Error"
    /photo/{photo_id}:
      get:
        tags:
          - photo
        summary: "Get specific photo"
        description: "Retrieve a specific photo by photo ID"
        parameters:
          - in: path
            name: photo_id
            required: true
            schema:
              type: string
        responses:
          '200':
            description: "Successful operation"
            content:
              multipart/form-data:
                schema:
                  type: string
                  format: binary
                example: "data:image/png;base64,SGVsbG8gV29ybGQhCg=="
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
          '500':
            description: "Internal Server Error"
    /photo:
      post:
        tags:
          - photo
        summary: "Upload photo"
        description: "Upload photo"
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                format: binary
        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  type: string
                  example: "photo_id"
          '401':
            description: "Unauthorized"
          '500':
            description: "Internal Server Error"
    /photos:
      get:
        tags:
        - photo
        summary: "Get user's photo IDs"
        description: "Retrieve a list of photo IDs owned by the user"
        responses:
          '200':
            description: "Successful operation"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: string
                example: ["photo_id_1", "photo_id_2"]
          '401':
            description: "Unauthorized"
          '404':
            description: "Not found"
          '500':
            description: "Internal Server Error"
    /mosaic_art:
      get:
        tags:
          - mosaic_art
        summary: "Get mosaic art"
        description: "Retrieve mosaic art"
        responses:
          '200':
            description: "Successful operation"
            content:
              multipart/form-data:
                schema:
                  type: string
                  format: binary
                example: "data:image/png;base64,SGVsbG8gV29ybGQhCg=="
          '401':
            description: "Unauthorized"
          '500':
            description: "Internal Server Error"
            
components:
  schemas:
    user:
      type: object
      properties:
        uid:
          type: integer
          description: UID
          example: 0123456789
        user_name:
          type: string
          description: User name
          example: ヤフー太郎
        candle_id:
          type: integer
          description: キャンドル ID
          example: 0123456789
        photo_ids:
          type: array
          items:
            type: string
          description: ユーザの全ての写真 ID
          example: ["photo_id_1", "photo_id_2", "photo_id_3"]
        pixel_coordinate:
          type: object
          description: モザイクアート中のどのピクセルに割り当てるか
          example: {row: 1, col: 2}
    candle:
      type: object
      properties:
        owner_id:
          type: integer
          description: Candle's owner
          example: 0123456789
        last_fired:
          type: string
          format: date-time
          description: Last fired date
  
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://example.com/oauth/authorize'
          scopes:
            read: Read access to protected resources
            write: Write access to protected resources