name: deploy
on:
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - 'README.md'
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ap-northeast-1
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      - name: CDK Deploy
        if: contains(github.event_name, 'push')
        run: npm run cdk:deploy
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
